### ISSUE TITLE
认证失败是什么原因啊

### ISSUE THREAD

**Issue by hyy313** [ciaoly/YingJiPuFa#2]
你好，出现这个问题：

请求访问：/error，认证失败，无法访问系统资源
{"msg":"请求访问：/error，认证失败，无法访问系统资源","code":401}
出错了.
稍等一会...

**Comment by ciaoly** [comment]
今天我在日志里也看到这个问题了，好像出问题的token里加了个gm参数，暂时不知道是什么原因。
